### PR TITLE
updated setup.py template to read setup metadata from existing json/yaml files.

### PR DESCRIPTION
**Pull request by JosephHobbs**
I noticed in the latest version of the SDK that it was reading the version file from the extension.yaml file.  My thought was, why not read the other parameters from the extension.yaml activationSchema.json files too?  This eliminates the need to duplicate things like author, version, etc...

### CODE REVIEW

**Comment by dlopes7** [comment]
This looks cool, but unfortunately we can't accept this as certain internal tools we use such as snyk would be unable to parse the setup.py file

When it parses it, it doesn't have access to the `extension.yaml` file and all of these would break.

**Comment by dlopes7** [comment]
We also can't add `pyyaml` as a dependency to every extension

**Comment by JosephHobbs** [comment]
I only used PyYaml because it's already a dependency in the SDK

**Comment by dlopes7** [comment]
Yes but adding it to `setup.py` makes it a requirement on the final extension build

**Pull request closed without merging**
